Repository tumfoodery/tripster, pull requests merged in 2020-01, with the labels that each got.

#2 Add clientside code
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/apple-touch-icon.png
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/App.test.js
  client/src/components/Copyright/index.js
  client/src/components/Login/index.js
  client/src/components/SignUp/index.js
  client/src/index.js
  client/src/resolvers/index.js
  client/src/schema/index.js
  client/src/serviceWorker.js
  client/src/setupTests.js
Labels: enhancement

#3 Apollo Server Setup
  server/README.md
  server/package-lock.json
  server/package.json
  server/src/datasources/firebase.js
  server/src/env.js
  server/src/index.js
  server/src/resolvers.js
  server/src/schema.js
Labels: enhancement

#4 Clean up imports
  client/src/components/SignUp/index.js
Labels: refactor

#5 Netlify function support
  server/.gitignore
  server/README.md
  server/netlify.toml
  server/package-lock.json
  server/package.json
  server/src/datasources/firebase.js
  server/src/env.js
  server/src/index.js
  server/src/lambda/graphql.js
  server/src/schema.js
  server/webpack.lambda.js
Labels: enhancement

#7 Add offline mode
  client/src/index.js
Labels: enhancement

#8 Connect GraphQL to the client
  client/README.md
  client/public/index.html
  client/src/App.js
  client/src/components/Copyright/index.js
  client/src/components/Login/index.js
  client/src/components/Login/useStyles.js
  client/src/components/SignUp/index.js
  client/src/components/SignUp/useStyles.js
  client/src/index.js
  client/src/schema/index.js
  server/src/lambda/graphql.js
Labels: enhancement

#9 Add More Queries and Mutations
  server/src/datasources/firebase.js
  server/src/resolvers.js
  server/src/schema.js
Labels: enhancement

#12 One Firebase Per Session
  server/src/datasources/firebase.js
  server/src/lambda/graphql.js
Labels: bug

#11 Updates to `/client`
  README.md
  client/.gitignore
  client/.storybook/main.ts
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/App.test.js
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/components/Copyright/index.js
  client/src/components/Copyright/index.tsx
  client/src/components/Home/index.tsx
  client/src/components/Input/Input.stories.tsx
  client/src/components/Input/index.tsx
  client/src/components/Login/index.js
  client/src/components/Login/index.tsx
  client/src/components/Login/useStyles.js
  client/src/components/SignUp/index.js
  client/src/components/SignUp/index.tsx
  client/src/components/SignUp/useStyles.js
  client/src/components/Trips/index.tsx
  client/src/index.js
  client/src/index.tsx
  client/src/resolvers/index.ts
  client/src/schema/index.js
  client/src/schema/index.ts
  client/src/serviceWorker.ts
  client/src/setupTests.ts
  client/tsconfig.json
  package.json
  server/.gitignore
Labels: enhancement

#15 Update README.md
  README.md
  client/public/apple-touch-icon.png
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon.ico
  client/public/logo192.png
  client/public/logo512.png
Labels: enhancement

#14 Firestore Integration and Structural Refactoring
  .gitignore
  server/package-lock.json
  server/package.json
  server/src/datasources/firebase.js
  server/src/datasources/firebaseAdmin.js
  server/src/datasources/firebaseClient.js
  server/src/lambda/graphql.js
  server/src/resolvers.js
  server/src/schema.js
Labels: enhancement

#17 Add Mutations for Password Reset Flow
  server/src/datasources/firebaseAdmin.js
  server/src/datasources/firebaseClient.js
  server/src/resolvers.js
  server/src/schema.js
Labels: enhancement

#16 Apollo Client / ThemeProvider
  .gitignore
  client/.storybook/config.js
  client/.storybook/main.ts
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/components/Button/Button.stories.tsx
  client/src/components/Button/index.tsx
  client/src/components/Copyright/Copyright.stories.tsx
  client/src/components/Input/Input.stories.tsx
  client/src/components/Input/index.tsx
  client/src/components/Login/index.tsx
  client/src/components/SignUp/index.tsx
  client/src/i18n/en-US.json
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/src/style/theme.ts
  client/src/styled.d.ts
  client/src/utils/fn.ts
  client/tsconfig.json
Labels: enhancement
